function RetarderMat = Retarder(radian,phaseDelay)
    RetarderMat = ...
    [cos(radian) -sin(radian);sin(radian) cos(radian);] ...
    *[exp(-1i*phaseDelay/2) 0;0 exp(1i*phaseDelay/2);] ...
    *[cos(radian) sin(radian);-sin(radian) cos(radian);];
end
